const states = [
  { name: "Alabama", active: false },
  { name: "Georgia", active: false },
  { name: "Louisiana", active: false },
  { name: "Montana", active: false },
  { name: "North Dakota", active: false },
  { name: "Tennessee", active: false },
  { name: "Alaska", active: false },
  { name: "Hawaii", active: false },
  { name: "Maine", active: false },
  { name: "Nebraska", active: false },
  { name: "Ohio", active: false },
  { name: "Texas", active: false },
  { name: "Arkansas", active: false },
  { name: "Idaho", active: false },
  { name: "Maryland", active: false },
  { name: "Nevada", active: false },
  { name: "Oklahoma", active: false },
  { name: "Utah", active: false },
  { name: "California", active: false },
  { name: "Illinois", active: false },
  { name: "Massachusetts", active: false },
  { name: "New Hampshire", active: false },
  { name: "Oregon", active: false },
  { name: "Vermont", active: false },
  { name: "Colorado", active: false },
  { name: "Indiana", active: false },
  { name: "Michigan", active: false },
  { name: "New Jersey", active: false },
  { name: "Pennsylvania", active: false },
  { name: "Virginia", active: false },
  { name: "Connecticut", active: false },
  { name: "Iowa", active: false },
  { name: "Minnesota", active: false },
  { name: "New Mexico", active: false },
  { name: "Rhode Island", active: false },
  { name: "Washington", active: false },
  { name: "Delaware", active: false },
  { name: "Kansas", active: false },
  { name: "Mississippi", active: false },
  { name: "New York", active: true },
  { name: "South Carolina", active: false },
  { name: "W. Virginia", active: false },
  { name: "Florida", active: false },
  { name: "Kentucky", active: false },
  { name: "Missouri", active: false },
  { name: "North Carolina", active: false },
  { name: "South Dakota", active: false },
  { name: "Wisconsin", active: false },
  { name: "Wyoming", active: false },
];

export default states;
